#!/usr/bin/env bash
# ==============================================================================
# Hospital Shield — Windows dev bootstrap (KHONG can Docker).
#
# Chay:
#   ./dev.sh          — setup .env.dev + DB + deps, khong start server
#   ./dev.sh up       — setup + chay backend (uvicorn) + frontend (vite) song song
#   ./dev.sh backend  — chi chay backend (port 3001)
#   ./dev.sh frontend — chi chay frontend (port 8080) — can backend dang chay
#   ./dev.sh seed     — ingest ./logs/ (Zeek logs) hoac mock data
#   ./dev.sh admin    — tao/update admin user (prompt interactive)
#   ./dev.sh reset    — DROP + CREATE database, wipe all data
#
# Yeu cau tren Windows (da check):
#   - Python 3.12+ (ban co 3.14)
#   - Node 20+      (ban co 24)
#   - PostgreSQL    (ban co 18 — chay service postgresql-x64-18)
# ==============================================================================

set -Eeuo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
    C_BOLD=$'\033[1m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_RED=$'\033[31m'; C_CYAN=$'\033[36m'; C_RESET=$'\033[0m'
else
    C_BOLD=; C_GREEN=; C_YELLOW=; C_RED=; C_CYAN=; C_RESET=
fi
log()  { printf '%s==>%s %s\n' "$C_CYAN" "$C_RESET" "$*"; }
ok()   { printf '%s ✓%s  %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn() { printf '%s ⚠%s  %s\n' "$C_YELLOW" "$C_RESET" "$*"; }
die()  { printf '%s ✗%s  %s\n' "$C_RED" "$C_RESET" "$*" >&2; exit 1; }

cd "$(dirname "$0")"

CMD="${1:-setup}"

# ── Config (override qua .env.dev neu muon) ─────────────────────────────────
DEV_DB_HOST="${DEV_DB_HOST:-localhost}"
DEV_DB_PORT="${DEV_DB_PORT:-5432}"
DEV_DB_NAME="${DEV_DB_NAME:-passive_asset_intel}"
DEV_DB_USER="${DEV_DB_USER:-postgres}"
DEV_DB_PASSWORD="${DEV_DB_PASSWORD:-doankhanh0212}"
DEV_API_PORT="${DEV_API_PORT:-3001}"
DEV_WEB_PORT="${DEV_WEB_PORT:-8080}"

# ── Helpers ─────────────────────────────────────────────────────────────────
venv_python() {
    if [[ -f .venv/Scripts/python.exe ]]; then
        echo ".venv/Scripts/python.exe"
    elif [[ -f .venv/bin/python ]]; then
        echo ".venv/bin/python"
    else
        die "venv chua tao — chay './dev.sh' truoc"
    fi
}

psql_cmd() {
    PGPASSWORD="$DEV_DB_PASSWORD" psql \
        -h "$DEV_DB_HOST" -p "$DEV_DB_PORT" -U "$DEV_DB_USER" "$@"
}

check_postgres() {
    if ! PGPASSWORD="$DEV_DB_PASSWORD" psql \
            -h "$DEV_DB_HOST" -p "$DEV_DB_PORT" -U "$DEV_DB_USER" \
            -d postgres -c 'SELECT 1' >/dev/null 2>&1; then
        warn "Khong connect duoc Postgres voi user=$DEV_DB_USER pass=$DEV_DB_PASSWORD"
        warn "Hay chinh DEV_DB_PASSWORD trong dev.sh (dong 39) hoac export truoc khi chay"
        die "Postgres check failed"
    fi
}

ensure_database() {
    if ! psql_cmd -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$DEV_DB_NAME'" | grep -q 1; then
        log "Tao database '$DEV_DB_NAME'"
        psql_cmd -d postgres -c "CREATE DATABASE $DEV_DB_NAME" >/dev/null
        ok "Database created"
    fi
    # Load schema neu table 'users' chua ton tai
    if ! psql_cmd -d "$DEV_DB_NAME" -tAc \
         "SELECT 1 FROM information_schema.tables WHERE table_name='users'" | grep -q 1; then
        log "Loading schema.sql"
        psql_cmd -d "$DEV_DB_NAME" -f passive_asset_intel/schema.sql >/dev/null
        ok "Schema loaded"
    fi
}

write_env_dev() {
    if [[ ! -f .env ]]; then
        log "Tao .env cho dev (Windows native)"
        cat > .env <<EOF
# Auto-generated by dev.sh — safe to edit.
DB_HOST=$DEV_DB_HOST
DB_PORT=$DEV_DB_PORT
DB_NAME=$DEV_DB_NAME
DB_USER=$DEV_DB_USER
DB_PASSWORD=$DEV_DB_PASSWORD
DB_POOL_MIN=2
DB_POOL_MAX=10

BATCH_SIZE=500
LOG_LEVEL=INFO

ZEEK_LOG_DIR=./logs
SCAN_MODE=file
ZEEK_INTERFACE=dev0
ZEEK_HOST_LOG_DIR=./logs

LOCAL_SUBNETS=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,103.98.152.0/24

JWT_SECRET_KEY=$(python -c "import secrets; print(secrets.token_hex(32))")

LOG_RETENTION_DAYS=30
API_CORS_ORIGINS=http://localhost,http://localhost:8080,http://localhost:5173
EOF
        ok ".env created (dev config)"
    else
        ok ".env already exists — leaving it alone"
    fi
}

ensure_venv() {
    if [[ ! -d .venv ]]; then
        log "Tao Python venv"
        python -m venv .venv
    fi
    PY="$(venv_python)"
    log "Cai Python deps (nhanh neu da cache)"
    "$PY" -m pip install --quiet --upgrade pip
    "$PY" -m pip install --quiet -r passive_asset_intel/requirements.txt
    ok "Python deps ready"
}

ensure_node_deps() {
    if [[ ! -d node_modules ]]; then
        log "Cai Node deps (npm ci — first run can take a minute)"
        npm ci --ignore-scripts
        ok "Node deps ready"
    else
        ok "node_modules already present"
    fi
}

# ── Commands ────────────────────────────────────────────────────────────────

cmd_setup() {
    write_env_dev
    check_postgres
    ensure_database
    ensure_venv
    ensure_node_deps
    echo
    ok "Dev env ready. Buoc ke tiep:"
    echo "    ./dev.sh admin     # tao admin user"
    echo "    ./dev.sh seed      # ingest ./logs/ vao DB"
    echo "    ./dev.sh up        # chay backend + frontend"
}

cmd_admin() {
    check_postgres
    ensure_database
    PY="$(venv_python)"
    read -r -p "Username admin: " USER_IN
    read -r -s -p "Password admin: " PASS_IN; echo
    [[ -n "$USER_IN" && -n "$PASS_IN" ]] || die "Username/password khong duoc de trong"
    "$PY" -m passive_asset_intel.scripts.create_admin \
        --username "$USER_IN" --password "$PASS_IN" --role admin
}

cmd_seed() {
    check_postgres
    ensure_database
    PY="$(venv_python)"
    if [[ -d ./logs ]] && ls ./logs/conn.log >/dev/null 2>&1; then
        log "Ingest Zeek logs tu ./logs (+ inference)"
        "$PY" -m passive_asset_intel run-all --log-dir ./logs
        ok "Zeek logs ingested"
    else
        warn "Khong thay ./logs/conn.log — dung mock data"
        "$PY" -m passive_asset_intel.scripts.seed_mock_data --assets 60
    fi
}

cmd_backend() {
    PY="$(venv_python)"
    log "Backend: http://localhost:$DEV_API_PORT  (Ctrl+C de dung)"
    "$PY" -m uvicorn passive_asset_intel.api.main:app \
        --host 0.0.0.0 --port "$DEV_API_PORT" --reload
}

cmd_frontend() {
    log "Frontend: http://localhost:$DEV_WEB_PORT  (Ctrl+C de dung)"
    npm run dev
}

cmd_up() {
    cmd_setup
    PY="$(venv_python)"
    log "Start backend (background) + frontend (foreground)"
    echo
    "$PY" -m uvicorn passive_asset_intel.api.main:app \
        --host 0.0.0.0 --port "$DEV_API_PORT" --reload &
    BACKEND_PID=$!
    trap "kill $BACKEND_PID 2>/dev/null || true" EXIT INT TERM
    sleep 3
    ok "Backend pid=$BACKEND_PID — http://localhost:$DEV_API_PORT"
    log "Frontend: http://localhost:$DEV_WEB_PORT"
    echo "${C_BOLD}Login:${C_RESET} mo http://localhost:$DEV_WEB_PORT sau khi frontend build xong"
    echo
    npm run dev
}

cmd_reset() {
    check_postgres
    warn "Se DROP database '$DEV_DB_NAME' — mat toan bo data dev. Continue?"
    read -r -p "Go 'yes' de xac nhan: " ANS
    [[ "$ANS" == "yes" ]] || { warn "Huy"; exit 0; }
    psql_cmd -d postgres -c "DROP DATABASE IF EXISTS $DEV_DB_NAME" >/dev/null
    ok "Database dropped"
    ensure_database
}

# ── Dispatch ────────────────────────────────────────────────────────────────
case "$CMD" in
    setup|"")     cmd_setup ;;
    up)           cmd_up ;;
    backend|api)  cmd_backend ;;
    frontend|web) cmd_frontend ;;
    seed|ingest)  cmd_seed ;;
    admin|user)   cmd_admin ;;
    reset)        cmd_reset ;;
    -h|--help|help)
        sed -n '2,18p' "$0"; exit 0 ;;
    *) die "Unknown command: $CMD (chay './dev.sh help')" ;;
esac
